name: Unit Tests.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.4]

    steps:
    - uses: actions/checkout@v3
    
    - name: Activate python virtual environment.
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install Necessary Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Tests.
      run: |
        python manage.py test
